### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by manuelmeurer** [zeke/gem.wtf#1]
Hey @zeke,

This is not a real issue, I just wanted to say that the idea for gem.wtf is really awesome! 😄 
It's one of these little things that you see, immediately think "huh, very useful, why hasn't this existed before?" and then start using every day. I've used it at least 20 times since I found it.
So congrats on building something actually useful! 👍

**Comment by zeke** [comment]
Thanks for the kind words @manuelmeurer! Glad you're finding it useful.
