### ISSUE TITLE
Dogfood failure: https://gem.wtf/gem.wtf leads to a 404

### ISSUE THREAD

**Issue by brandonzylstra** [zeke/gem.wtf#2]
I assumed that gem.wtf would work for itself, but https://gem.wtf/gem.wtf leads to a 404 on the Rubygems web site.  I have no idea whether that's a configuration failure or a bug, or a false assumption on my part (such as expecting dots in the gem name to be preserved).  If the last of these, then I would still consider it to be either a usability issue (working differently than expected) or at least a documentation issue (no examples of disappearing dots in the examples on https://gem.wtf).

**Comment by zeke** [comment]
gem.wtf is not itself a ruby gem...

**Comment by brandonzylstra** [comment]
haha sorry... what was I thinking 😅
